Added 2 calls for creating dgeAnalysis input files
biowdl/RNA-seq pull request #76
Opened 2020-10-07 15:16 UTC by tomkuipers1402

### Checklist
- [ ] Pull request details were added to CHANGELOG.md
- [ ] Documentation was updated (if required).

2020-10-08 07:02 UTC, Redmar-van-den-Berg approved these changes

2020-10-22 04:41 UTC, Redmar-van-den-Berg approved these changes

2020-10-22 11:22 UTC, DavyCats requested changes
The output from these tasks should also be added to the workflow output.

2020-10-22 11:22 UTC, DavyCats commented on CHANGELOG.md
> ++ Add call to create samplesheet template for shiny app
```suggestion
+ Add call to create annotation file for shiny app.
+ Add call to create samplesheet template for shiny app.
```

2020-10-22 18:49 UTC, DavyCats approved these changes

2020-12-22 12:06 UTC, closed without merging